# Server Configuration
server:
  port: 8080
  undertow:
    worker-threads: 200
  servlet:
    session:
      persistent: false
      store-dir: /var/log/app

# Oracle settings and Pool Connection
spring:
  application:
    name: cadastro-spring-booot
  datasource:
    url: jdbc:oracle:thin:@10.20.1.111:1522:OMNIDEV
    username: WSCADASTRO
    password: omnidev
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: cadastroPool
      idle-timeout: 9000
      isolate-internal-queries: true
      connection-test-query: SELECT 1 from DUAL
      connection-timeout: 18000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: true
        format_sql: true

