spring:
  application:
    name: exemplos-sping
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true